snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ${{ secrets.SNOWFLAKE_ACCOUNT }} # Snowflake <account_name>
      user: ${{ secrets.SNOWFLAKE_USER }} # Snowflake username
      password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      role: ${{ secrets.SNOWFLAKE_ROLE }} # Snowflake user role

      # SSO config
      # authenticator: externalbrowser

      database: DBT_PROJECT # Snowflake database name
      warehouse: COMPUTE_WH # Snowflake warehouse name
      schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
      threads: 4
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false
