snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_USERNAME') }}" # Snowflake <account_name>
      user: "{{ env_var('DBT_SNOWFLAKE_USERNAME') }}" # Snowflake username
      password: "{{ env_var('DBT_SNOWFLAKE_PW') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}" # Snowflake user role

      # SSO config
      # authenticator: externalbrowser

      database: DBT_PROJECT # Snowflake database name
      warehouse: COMPUTE_WH # Snowflake warehouse name
      schema: DEV
      threads: 4
      client_session_keep_alive: False

    prod:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_USERNAME') }}" # Snowflake <account_name>
      user: "{{ env_var('DBT_SNOWFLAKE_USERNAME') }}" # Snowflake username
      password: "{{ env_var('DBT_SNOWFLAKE_PW') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}" # Snowflake user role
      database: DBT_PROJECT # Snowflake database name
      warehouse: COMPUTE_WH # Snowflake warehouse name
      schema: PROD
      threads: 4
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false
