version: 2
# the following are the 4 default tests that can be given to any of the models.
models:
  - name: stg_call_center
    columns:
      - name: CC_CALL_CENTER_SK
        tests:
          - unique
          - not_null
      - name: CC_CALL_CENTER_ID
        tests:
          - unique
          - not_null
#        tests:
#          - accepted_values:
#              values: ['placed', 'shipped', 'completed', 'returned']
#      - name: column3
#        tests:
#          - relationships:
#              to: ref('customers')
#              field: id
#      - name: amount_usd
#        tests:
#          - not_null
#          - greater_than_zero # generic test
